let users=[];const table=document.querySelector('#userTable'),emptyState=document.querySelector('#emptyState'),search=document.querySelector('#search'),roleFilter=document.querySelector('#roleFilter'),statusFilter=document.querySelector('#statusFilter'),modal=document.querySelector('#modal'),toast=document.querySelector('#toast');
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function initials(n){return n.split(' ').filter(Boolean).map(p=>p[0]).join('').slice(0,2).toUpperCase();}
function render(){const q=search.value.toLowerCase().trim();const filtered=users.filter(u=>`${u.name} ${u.email}`.toLowerCase().includes(q)&&(roleFilter.value==='all'||u.role===roleFilter.value)&&(statusFilter.value==='all'||u.status===statusFilter.value));table.innerHTML=filtered.map((u,i)=>`<tr><td><input type="checkbox"></td><td class="user-cell"><span class="user-avatar avatar-${i%5}">${esc(initials(u.name))}</span><span>${esc(u.name)}<small>${esc(u.email)}</small></span></td><td class="role">${esc(u.role)}</td><td><span class="status ${u.status==='Ожидает активации'?'pending':u.status==='Заблокирован'?'blocked':''}">${esc(u.status)}</span></td><td>${esc(u.lastLogin)}</td><td><button class="row-menu">•••</button></td></tr>`).join('');emptyState.style.display=filtered.length?'none':'block';document.querySelector('#resultCount').textContent=`Показано ${filtered.length} из ${users.length} пользователей`;document.querySelector('#userCount').textContent=users.length;document.querySelector('#totalUsers').textContent=users.length;document.querySelector('#pendingUsers').textContent=users.filter(u=>u.status==='Ожидает активации').length;document.querySelector('#blockedUsers').textContent=users.filter(u=>u.status==='Заблокирован').length;}
function showToast(m){toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);}function closeModal(){modal.classList.remove('open');}
[search,roleFilter,statusFilter].forEach(c=>c.addEventListener('input',render));document.querySelector('#resetFilters').onclick=()=>{search.value='';roleFilter.value='all';statusFilter.value='all';render();};document.querySelector('#selectAll').onchange=e=>table.querySelectorAll('input[type=checkbox]').forEach(b=>b.checked=e.target.checked);document.querySelector('#addUser').onclick=()=>modal.classList.add('open');document.querySelector('#closeModal').onclick=closeModal;document.querySelector('#cancelModal').onclick=closeModal;
document.querySelector('#userForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const r=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),email:f.get('email'),role:f.get('role')})});const p=await r.json().catch(()=>({}));if(!r.ok)return showToast(p.error||'Ошибка создания');await loadUsers();e.target.reset();closeModal();showToast('Пользователь создан');});
document.querySelector('#exportUsers').onclick=()=>{const cell=v=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=['Имя,Email,Роль,Статус,Последний вход',...users.map(u=>[u.name,u.email,u.role,u.status,u.lastLogin].map(cell).join(','))].join('\n');const url=URL.createObjectURL(new Blob([`\uFEFF${csv}`],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='edulink-users.csv';a.click();URL.revokeObjectURL(url);};
async function loadUsers(){const r=await fetch('/api/users');if(!r.ok)throw new Error('Нет доступа');users=await r.json();render();}
function redirectByRole(role){if(role==='teacher')location.href='/teacher.html';else if(role==='student')location.href='/student.html';}
async function checkSession(){const r=await fetch('/api/session');if(!r.ok)return;const a=await r.json();if(a.role!=='admin'){redirectByRole(a.role);return;}document.querySelector('#authScreen').classList.add('hidden');await loadUsers();}
document.querySelector('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:f.get('email'),password:f.get('password')})});const a=await r.json().catch(()=>({}));if(!r.ok){document.querySelector('#authError').textContent=a.error||'Ошибка входа';return;}if(a.role!=='admin'){redirectByRole(a.role);return;}document.querySelector('#authScreen').classList.add('hidden');await loadUsers();});document.querySelector('#logout').onclick=async()=>{await fetch('/api/logout',{method:'POST'});location.reload();};checkSession();