(() => {
  const content=document.querySelector('#content'), notice=document.querySelector('#notice');
  const params=new URLSearchParams(location.search), lessonId=params.get('lesson');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const attendance={unmarked:'Не отмечено',present:'Присутствовал',late:'Опоздал',absent:'Отсутствовал',excused:'Уважительная причина'};
  const date=v=>new Date(v).toLocaleString('ru-RU',{dateStyle:'short',timeStyle:'short'});
  const points=v=>v===null?'Не выставлен':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(v);
  let dirty=false,poll,session;
  async function api(url,method='GET',body){const r=await fetch(url,{method,...(body!==undefined?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.error||`Ошибка ${r.status}`);return d;}
  const error=e=>{notice.style.color='#ac3838';notice.textContent=e.message;};
  function testText(t){return !t.total?'Тестов нет':`${t.points===null?'Нет завершённых попыток':points(t.points)+' / '+t.max} · завершено ${t.completed}/${t.total}${t.running?' · выполняет: '+t.running:''}${t.pending?' · свободных ответов на проверке: '+t.pending:''}`;}
  async function journal(){
    clearInterval(poll);const d=await api('/api/journal/lessons/'+lessonId);dirty=false;
    document.querySelector('#title').textContent='Журнал занятия';
    content.innerHTML=`<section class="card"><h2>${esc(d.lesson.title)}</h2><p>${esc(d.lesson.courseName)} · ${esc(d.lesson.groupName)} · ${esc(d.lesson.status)}</p><div class="actions"><a class="button" href="/learning.html?lesson=${lessonId}">План и тестирование</a><a class="button" href="/journal.html?course=${d.lesson.courseId}">Рейтинг дисциплины</a>${d.canEdit&&d.lesson.status!=='Проведено'?'<button id="complete">Отметить занятие проведённым</button>':''}</div></section>
      <section class="card"><div class="card-head"><h2>Посещение и баллы</h2><button id="reload">Обновить журнал</button></div><p class="muted">Итоговый балл: 0–100. В рейтинг входит только итоговый балл преподавателя — баллы тестов повторно не прибавляются. Пустое поле означает, что оценка ещё не выставлена, а 0 — выставленную нулевую оценку.</p>
      ${!d.canGrade?'<p class="muted">Итоговые баллы доступны после окончания занятия. Посещаемость можно отметить сейчас.</p>':''}
      <form id="journalForm"><div class="table-wrap"><table class="marks"><thead><tr><th>Студент</th><th>Посещение</th><th>Тесты — автоматически</th><th>Итоговый балл</th><th>Комментарий студенту</th></tr></thead><tbody>${d.rows.map(s=>`<tr data-student="${s.studentId}"><td>${esc(s.name)}</td><td><select name="attendance" aria-label="Посещение: ${esc(s.name)}" ${!d.canEdit?'disabled':''}>${Object.entries(attendance).map(([v,l])=>`<option value="${v}" ${v===s.attendance?'selected':''}>${l}</option>`).join('')}</select></td><td data-tests="${s.studentId}">${esc(testText(s.tests))}</td><td><input type="number" name="finalScore" aria-label="Итоговый балл: ${esc(s.name)}" min="0" max="100" step="0.01" value="${s.finalScore===null?'':s.finalScore}" ${!d.canEdit||!d.canGrade?'disabled':''}></td><td><textarea name="note" aria-label="Комментарий: ${esc(s.name)}" maxlength="2000" ${!d.canEdit?'disabled':''}>${esc(s.note)}</textarea></td></tr>`).join('')}</tbody></table></div>${!d.rows.length?'<p class="muted">В группе пока нет студентов.</p>':''}<p id="saveState" class="muted" aria-live="polite">Журнал загружен. Баллы тестов обновляются каждые 5 секунд.</p>${d.canEdit&&d.rows.length?'<button type="submit" class="primary">Сохранить журнал</button>':''}</form></section>`;
    const form=document.querySelector('#journalForm');form.oninput=()=>{dirty=true;document.querySelector('#saveState').textContent='Есть несохранённые изменения';};
    form.onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{
      const rows=[...form.querySelectorAll('[data-student]')].map(tr=>({studentId:tr.dataset.student,attendance:tr.querySelector('[name=attendance]').value,finalScore:tr.querySelector('[name=finalScore]').value===''?null:Number(tr.querySelector('[name=finalScore]').value),note:tr.querySelector('[name=note]').value}));
      const r=await api('/api/journal/lessons/'+lessonId,'PUT',{version:d.version,rows});d.version=r.version;dirty=false;notice.textContent='';document.querySelector('#saveState').textContent='Журнал сохранён. Рейтинг пересчитан.';
    }catch(e){error(e);}finally{b.disabled=false;}};
    document.querySelector('#reload').onclick=()=>{if(!dirty||confirm('Обновить журнал и отменить несохранённые изменения?'))journal().catch(error);};
    const complete=document.querySelector('#complete');if(complete)complete.onclick=async()=>{if(dirty){error(new Error('Сначала сохраните посещаемость и комментарии'));return;}if(!confirm('Подтвердить, что занятие завершено?'))return;try{await api('/api/journal/lessons/'+lessonId+'/complete','POST',{});await journal();}catch(e){error(e);}};
    poll=setInterval(async()=>{try{const fresh=await api('/api/journal/lessons/'+lessonId);for(const s of fresh.rows){const el=content.querySelector(`[data-tests="${s.studentId}"]`);if(el)el.textContent=testText(s.tests);}if(fresh.canGrade!==d.canGrade||fresh.rows.length!==d.rows.length){document.querySelector('#saveState').textContent='Статус занятия или состав группы изменился. Обновите журнал после сохранения.';}}catch(e){error(e);}},5000);
  }
  async function rankings(){
    const courses=await api('/api/journal/courses');document.querySelector('#title').textContent=session.role==='student'?'Мои баллы и рейтинг':'Рейтинг по дисциплине';
    content.innerHTML=`<section class="card"><label>Дисциплина<select id="courseSelect"><option value="">Выберите дисциплину</option>${courses.map(c=>`<option value="${c.id}">${esc(c.code)} · ${esc(c.name)}</option>`).join('')}</select></label>${!courses.length?'<p class="muted">Доступных дисциплин пока нет.</p>':''}</section><section id="ranking"></section>`;
    const select=document.querySelector('#courseSelect');
    async function load(){
      const out=document.querySelector('#ranking'),id=select.value;if(!id){out.innerHTML='';return;}const d=await api('/api/journal/courses/'+id);if(select.value!==id)return;
      history.replaceState(null,'','/journal.html?course='+id);notice.textContent='';
      out.innerHTML=`<section class="card"><div class="card-head"><h2>${esc(d.course.name)}</h2><div class="actions"><button id="refreshRating">Обновить</button>${d.role!=='student'?'<button id="exportRating">Экспорт CSV</button>':''}</div></div><p class="muted">Рейтинг = сумма выставленных итоговых баллов за завершившиеся занятия дисциплины. Отменённые занятия исключены. При равной сумме — одинаковое место. Без оценок место пока не определяется.</p><div class="table-wrap"><table><thead><tr><th>Место</th><th>Студент</th><th>Сумма баллов</th><th>Оценено занятий</th><th>Посетил</th><th>Пропустил</th><th>Уваж. причина</th></tr></thead><tbody>${d.rows.map(s=>`<tr class="${d.role==='student'?'mine':''}"><td>${s.rank===null?'—':s.rank}</td><td>${esc(s.name)}</td><td><strong>${points(s.total)}</strong></td><td>${s.graded}</td><td>${s.attended}</td><td>${s.absent}</td><td>${s.excused}</td></tr>`).join('')}</tbody></table></div><p class="muted">Студентов в дисциплине: ${d.totalStudents}. Опоздание учитывается как посещение.</p></section>
      <section class="card"><h2>${d.role==='student'?'Мои оценки по занятиям':'Занятия дисциплины'}</h2><div class="table-wrap"><table><thead><tr><th>Дата</th><th>Занятие</th><th>Статус</th>${d.role==='student'?'<th>Посещение</th><th>Итоговый балл</th><th>Комментарий</th>':'<th>Журнал</th>'}</tr></thead><tbody>${d.lessons.map(l=>`<tr><td>${date(l.startsAt)}</td><td>${esc(l.title)}</td><td>${esc(l.status)}</td>${d.role==='student'?`<td>${attendance[l.attendance]}</td><td>${points(l.finalScore)}${l.status==='Отменено'?' (не учитывается)':''}</td><td>${esc(l.note)}</td>`:`<td>${l.canViewJournal?`<a class="button" href="/journal.html?lesson=${l.id}">Открыть</a>`:"Другой преподаватель"}</td>`}</tr>`).join('')}</tbody></table></div></section>`;
      document.querySelector('#refreshRating').onclick=()=>load().catch(error);
      const exp=document.querySelector('#exportRating');if(exp)exp.onclick=()=>{const cell=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,x=>"'"+x).replace(/"/g,'""')+'"';const rows=[['Место','Студент','Баллы','Оценено занятий','Посетил','Пропустил','Уважительная причина'],...d.rows.map(s=>[s.rank,s.name,s.total,s.graded,s.attended,s.absent,s.excused])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='edulink-rating.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
    }
    select.onchange=()=>load().catch(error);const initial=params.get('course');if(courses.some(c=>String(c.id)===initial)){select.value=initial;await load();}else if(courses.length===1){select.value=courses[0].id;await load();}
  }
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
  (async()=>{session=await api('/api/session');document.querySelector('#back').href=session.role==='teacher'?'/teacher.html':session.role==='student'?'/student.html':'/';if(lessonId){if(!/^\d+$/.test(lessonId))throw new Error('Некорректное занятие');await journal();}else await rankings();})().catch(e=>{error(e);content.textContent='Не удалось загрузить данные. Проверьте вход и права доступа.';});
})();
