const connectionText=document.querySelector('#connectionText'),stateText=document.querySelector('#participantState'),roomTimer=document.querySelector('#roomTimer'),localVideo=document.querySelector('#localVideo'),remoteVideo=document.querySelector('#remoteVideo'),localFeed=document.querySelector('#localFeed'),remoteFeed=document.querySelector('#remoteFeed'),micButton=document.querySelector('#mic'),cameraButton=document.querySelector('#camera'),screenButton=document.querySelector('#screen');let viewer='student',localStream=new MediaStream(),peer=null,iceServers=[{urls:'stun:stun.l.google.com:19302'}],pending=[],timer=null,screenTrack=null;
async function json(r){const b=await r.json();if(!r.ok)throw new Error(b.error||'Ошибка');return b;}async function signal(type,payload){const target=viewer==='teacher'?'student':'teacher';await json(await fetch('/api/video/signals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target,type,payload})}));}
function labels(){const teacher=viewer==='teacher';document.querySelector('#localName').textContent=teacher?'Преподаватель (вы)':'Студент (вы)';document.querySelector('#localRole').textContent=teacher?'Преподаватель · локальное видео':'Студент · локальное видео';document.querySelector('#remoteName').textContent=teacher?'Студент':'Преподаватель';document.querySelector('#remoteRole').textContent=teacher?'Студент':'Преподаватель';document.querySelector('#documentEditorLabel').textContent=teacher?'Редактирует: преподаватель':'Редактирует: студент';}
async function media(){localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:true});localVideo.srcObject=localStream;localFeed.classList.add('has-video');}
function makePeer(){if(peer)peer.close();peer=new RTCPeerConnection({iceServers});localStream.getTracks().forEach(t=>peer.addTrack(t,localStream));peer.onicecandidate=e=>{if(e.candidate)signal('ice',e.candidate.toJSON()).catch(console.error)};peer.ontrack=e=>{remoteVideo.srcObject=e.streams[0];remoteFeed.classList.add('has-video')};peer.onconnectionstatechange=()=>{if(peer.connectionState==='connected'){connectionText.textContent='Соединение установлено';stateText.textContent='Онлайн-занятие идет';}else if(peer.connectionState==='failed')connectionText.textContent='Не удалось установить соединение — проверьте TURN';};}
async function offer(){if(viewer!=='teacher')return;const o=await peer.createOffer();await peer.setLocalDescription(o);await signal('offer',peer.localDescription.toJSON());}
async function handle(m){if(!peer)makePeer();if(m.type==='offer'){await peer.setRemoteDescription(m.payload);for(const c of pending.splice(0))await peer.addIceCandidate(c);const a=await peer.createAnswer();await peer.setLocalDescription(a);await signal('answer',peer.localDescription.toJSON());}else if(m.type==='answer'){await peer.setRemoteDescription(m.payload);for(const c of pending.splice(0))await peer.addIceCandidate(c);}else if(m.type==='ice'){if(peer.remoteDescription)await peer.addIceCandidate(m.payload);else pending.push(m.payload);}}
async function poll(){try{const d=await json(await fetch('/api/video/signals'));for(const m of d.messages)await handle(m);}catch(e){console.error(e);}setTimeout(poll,1000);}
async function room(){const r=await json(await fetch('/api/video/room'));const both=r.teacherJoined&&r.studentJoined;connectionText.textContent=both?'Оба участника подключены, устанавливаем соединение…':viewer==='teacher'?'Ожидание студента':'Ожидание преподавателя';stateText.textContent=both?'Согласование WebRTC':'Онлайн-занятие начнется после подключения обоих участников';if(r.startedAt&&!timer)timer=setInterval(()=>roomTimer.textContent=new Date(Date.now()-r.startedAt).toISOString().substring(14,19),1000);if(both&&viewer==='teacher'&&(!peer||peer.connectionState==='new')){makePeer();await offer();}setTimeout(room,1500);}
micButton.onclick=()=>{const t=localStream.getAudioTracks()[0];if(t){t.enabled=!t.enabled;micButton.classList.toggle('muted',!t.enabled)}};cameraButton.onclick=()=>{const t=localStream.getVideoTracks()[0];if(t){t.enabled=!t.enabled;cameraButton.classList.toggle('muted',!t.enabled)}};screenButton.onclick=async()=>{if(screenTrack){screenTrack.stop();screenTrack=null;return;}const s=await navigator.mediaDevices.getDisplayMedia({video:true});screenTrack=s.getVideoTracks()[0];const sender=peer&&peer.getSenders().find(x=>x.track?.kind==='video');if(sender)await sender.replaceTrack(screenTrack);screenTrack.onended=async()=>{const cam=localStream.getVideoTracks()[0];if(sender&&cam)await sender.replaceTrack(cam);screenTrack=null;};};async function leave(){try{await json(await fetch('/api/video/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'leave'})}));}catch{}localStream.getTracks().forEach(t=>t.stop());location.href=viewer==='teacher'?'/teacher.html':'/student.html';}document.querySelector('#leave').onclick=leave;document.querySelector('#end').onclick=leave;
(async()=>{try{const s=await json(await fetch('/api/session'));viewer=s.role;if(!['teacher','student'].includes(viewer))return location.href='/';labels();iceServers=(await json(await fetch('/api/video/ice-config'))).iceServers;await media();await json(await fetch('/api/video/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'join'})}));poll();room();}catch(e){connectionText.textContent=e.message;}})();